import { useCallback, useRef, useState } from "react";
import { toast } from "sonner";

type UseYoutubeVideoProps = {
  videoId: string;
};

export function useYoutubeVideo({ videoId }: UseYoutubeVideoProps) {
  const description = `Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book.`;

  const summary = `Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.`;

  const views = 123124;
  const likes = 775419;
  const comments = 42424242;
  const transcript = predefined;

  return { description, summary, views, likes, comments, transcript };
}
const predefined = [
  "[00:00] I'm going to walk you through a",
  "[00:00] four-step process that I think puts",
  "[00:03] business on easy mode. And so whether",
  "[00:05] you're just getting started or you're",
  "[00:06] already making tons of money and are",
  "[00:08] just trying to make more, this process",
  "[00:10] just works. And I've done it in tons of",
  "[00:13] different portfolio companies and",
  "[00:14] companies we've advised. Um, and just to",
  "[00:16] give you a little bit of context, um, as",
  "[00:18] of last year, our portfolio at",
  "[00:20] acquisition.com did over $250 million in",
  "[00:22] aggregate revenue. And I say that not as",
  "[00:24] a promise that if you do this, you're",
  "[00:26] going to get that outcome, but that this",
  "[00:27] works. All right, so that being said,",
  "[00:29] let's dive in. Step number one, get the",
  "[00:31] ad. So, we have to fundamentally show",
  "[00:34] something to someone in order for them",
  "[00:37] to find out about our stuff, right? Can",
  "[00:39] we agree on that? If the answer to that",
  "[00:40] is yes, then the first step here is that",
  "[00:43] we're going to have some sort of",
  "[00:45] advertisement. Now, that ad might be",
  "[00:48] somebody reaching out. It's an",
  "[00:49] advertisement, literally letting people",
  "[00:50] know about stuff. It could be a paid ad,",
  "[00:52] so it could be an interruptionbased ad",
  "[00:54] that happens, you know, on any social",
  "[00:56] media platform. It could be a piece of",
  "[00:58] content like this that says, Hey, you",
  "[01:00] know, go buy this thing. Now, between",
  "[01:02] all the different ways of getting",
  "[01:03] customers, paid ads versus content",
  "[01:06] versus outreach versus maybe the",
  "[01:08] exception being affiliates, paid ads is",
  "[01:11] the most, you know, the the fastest to",
  "[01:13] scale because one guy with buttons and",
  "[01:15] good creative could scale it to the",
  "[01:17] mood, right? And so, it's all about",
  "[01:19] skill when it comes to creating paid",
  "[01:20] ads. Now, I'm going to just use this as",
  "[01:23] our placeholder, but if you're trying to",
  "[01:24] get into paid ads, uh, then I'll give",
  "[01:26] you two little frameworks that have",
  "[01:27] worked really well for me. All right, so",
  "[01:29] number one, and this is a new one, which",
  "[01:31] is absolutely murdering it for us, is",
  "[01:33] what I'll call organic plus CTA. Very",
  "[01:38] complicated. All right, so what is",
  "[01:40] organic plus CTA? It's you have whatever",
  "[01:43] organic content you make. Some content",
  "[01:45] does better than others, provided you",
  "[01:46] make organic content relevant to the",
  "[01:48] stuff you sell, which by the way,",
  "[01:49] probably a good idea. Um, you make your",
  "[01:52] content and then you find the good ones.",
  "[01:53] And then all you do is you add a call to",
  "[01:55] action at the end that sends people to",
  "[01:56] your thing and we already know it works",
  "[01:59] because we've already tried it. And so",
  "[02:01] you get to have all these test shots on",
  "[02:03] goal that cost you nothing by simply",
  "[02:05] making the content. And then you just",
  "[02:06] let the algorithm tell you what people",
  "[02:08] already like and they engage with and",
  "[02:09] they share and they click, they get past",
  "[02:11] the hook and then you just say, Oh, I'm",
  "[02:13] going to take this thing and I'm going",
  "[02:14] to turn into something that feeds my",
  "[02:15] business in a more scalable way because",
  "[02:17] I'm not going to rely on the platform to",
  "[02:19] just give it to people for free, which",
  "[02:20] is great. But I also can't really add a",
  "[02:23] longer call to action because it would",
  "[02:25] tank the effectiveness of the clip. But",
  "[02:27] if I put it in the beginning and then I",
  "[02:29] pay the platform, then they're happy to",
  "[02:31] display it because they were already",
  "[02:32] happy to display it for free. So why",
  "[02:33] wouldn't they want to display it in",
  "[02:34] exchange for money? And then we can add",
  "[02:36] our very simple call to action at the",
  "[02:38] end for some sort of thing which I'll",
  "[02:40] get to in a second. Now the second kind",
  "[02:42] of way of thinking about this like this",
  "[02:44] one's by far the easiest. If you can do",
  "[02:45] this do it. Now if you're like okay I",
  "[02:47] don't have enough organic or you know I",
  "[02:49] just need to you know quickly make ads",
  "[02:51] directly then this is the framework that",
  "[02:52] I would use. So I have hook plus meat",
  "[02:56] plus CTA. All right. So I'm going to",
  "[02:58] break down each of these really quickly.",
  "[02:59] So from a hook's perspective, what I do",
  "[03:01] is I still look at the best performing",
  "[03:03] organic and the best performing ads",
  "[03:05] across all industries. So this is one",
  "[03:07] where you don't need to stick to your",
  "[03:08] industry. You might find a hook that",
  "[03:09] works exceptionally well in finance and",
  "[03:12] it works really well for hotels too,",
  "[03:14] right? Provided it doesn't like actually",
  "[03:15] say finance in it. And so you'll see",
  "[03:17] that hooks just convert across way",
  "[03:19] different audiences because it just",
  "[03:20] draws attention. And so the first thing",
  "[03:22] I'll look at is hooks. And this is by",
  "[03:23] far the 80% of the ad. And you're like,",
  "[03:26] Wait, but they're so short and they're",
  "[03:27] still the most important. So, we should",
  "[03:28] just be thankful. It's crazy. It's like",
  "[03:30] people have a hard time accepting that",
  "[03:32] something short could be more meaningful",
  "[03:34] than something long because it takes",
  "[03:36] more work. Like, would you prefer that",
  "[03:38] the thing that means the most is",
  "[03:39] actually really hard and long to do? No.",
  "[03:42] Right? Like the fact that hooks are",
  "[03:43] short is a gift from God for advertisers",
  "[03:46] that we can actually have the most",
  "[03:47] important thing not require a ton of",
  "[03:48] work. Now, if you want to be smart about",
  "[03:49] it, it should require work because",
  "[03:51] you're going to do that work in the",
  "[03:52] research or the pre-search before you",
  "[03:53] record this. So, for here, I would have",
  "[03:56] at least 50 plus hooks. Now, you're",
  "[03:58] like, 50 plus hooks? Yeah, you're",
  "[04:00] probably not making nearly enough ads.",
  "[04:02] And I don't care what your spend is.",
  "[04:03] Like, if you're spending $10,000 a",
  "[04:05] month, $100,000 a month, like, you can",
  "[04:06] never have too many",
  "[04:08] ads. I'll just say that. You can never",
  "[04:10] have too many ads. You just give the",
  "[04:12] algorithm more things to pick from to",
  "[04:13] find the winners. Now, the meat, I'm",
  "[04:15] going to give you a different framework",
  "[04:17] that I haven't talked about much lately.",
  "[04:19] And so, I'm going to break it down for",
  "[04:20] you right here. All right. This is",
  "[04:22] fourstep persuasion. And I just think",
  "[04:24] it's just so easy to understand. So this",
  "[04:27] is how I think this is my mental",
  "[04:28] framework, all right, for how I actually",
  "[04:30] make persuasive advertisements, copy,",
  "[04:32] pitches, whatever, right? Which is",
  "[04:35] you're going to get more good stuff if",
  "[04:37] you do the thing I want you to do.",
  "[04:39] You're going to get less bad stuff if",
  "[04:41] you do the thing I want you to do. And",
  "[04:42] if you don't do the thing that I want",
  "[04:44] you to do, you're going to get more bad",
  "[04:45] stuff. And you're going to get less good",
  "[04:47] stuff. That's it. Four different angles",
  "[04:49] that you can hit on any action I want",
  "[04:51] you to take. So, if you sign up for the",
  "[04:53] gym, you're going to feel better. I'm",
  "[04:56] making this obviously really simple.",
  "[04:58] You're gonna get more good feels. You're",
  "[04:59] have more energy. You're going to have",
  "[05:01] you're going to sleep better. All that",
  "[05:02] stuff's good. Now, what's the inverse of",
  "[05:04] that? You're not going to feel the brain",
  "[05:05] fog that you've been feeling. You're not",
  "[05:06] going to feel as lethargic. Um you're",
  "[05:09] not going to have your kids out playing",
  "[05:11] and feel like you can't play with them",
  "[05:12] and feel like a bad parent. We're going",
  "[05:13] to get rid of all that minus negative",
  "[05:15] thing. The only thing easier, you know,",
  "[05:17] than taking this small action today is",
  "[05:19] not taking that action. But the thing is",
  "[05:21] is that if you don't take that action,",
  "[05:22] then whatever brain fog you're feeling",
  "[05:24] right now, the current weight that you",
  "[05:25] put on the last 5 years, let's push it",
  "[05:27] out two or three years, how much more",
  "[05:28] weight are you going to be? Like if",
  "[05:29] you're if you're 50 pounds overweight",
  "[05:31] now, what are you going to feel like at",
  "[05:32] 70 lbs overweight? It'd be it'd be way",
  "[05:34] worse, right? You don't want that. Also,",
  "[05:36] all those memories, when you think about",
  "[05:37] the happiest memories that you have with",
  "[05:39] your kids, with your family, like those",
  "[05:41] are going to decrease. You're going to",
  "[05:42] have fewer of those because you",
  "[05:44] physically can't do that. And so, the",
  "[05:46] only thing easier than not take than",
  "[05:47] taking action is not taking action at",
  "[05:49] all. And so if these are the things that",
  "[05:50] you want, you should do this thing",
  "[05:51] because that way we can avoid this",
  "[05:53] stuff. That's it. Very straightforward.",
  "[05:55] And this is what",
  "[05:57] constitutes our meat. Now I did a very",
  "[06:00] simplistic example. If I want to make",
  "[06:02] that more interesting, right? And if you",
  "[06:04] want to like how do you create unique",
  "[06:05] copy? This is a little advanced tip for",
  "[06:07] you. All right. So pro tip, break down",
  "[06:09] the terms. So what does it mean? So if I",
  "[06:12] say you're going to feel better, right?",
  "[06:15] That is not going to be compelling copy.",
  "[06:16] I can promise you that right now. But",
  "[06:17] what does feel better mean to somebody?",
  "[06:19] How would I know that feeling better had",
  "[06:21] occurred right in their life? And this",
  "[06:23] is where you have to this is where the",
  "[06:24] the research of like reading Amazon",
  "[06:26] reviews for products that are similar in",
  "[06:28] your space. Even if you sell services,",
  "[06:30] read the positive reviews in their",
  "[06:32] language of the things that they will",
  "[06:34] say of why of what happened. What were",
  "[06:36] the and the way I think about this here",
  "[06:38] it is this is it. This is the big word",
  "[06:40] that you need to double underline. Think",
  "[06:42] in moments. What is the moment that",
  "[06:44] someone think wow I feel better? What's",
  "[06:46] the moment? what occurred, what",
  "[06:47] happened, right? Maybe it's that they",
  "[06:50] were able, let's say if it's an elderly",
  "[06:51] population that were doing with this",
  "[06:52] weight loss thing, um they were able to",
  "[06:54] take the kid off the ground and pick him",
  "[06:56] up, right? And they have this moment",
  "[06:58] where after they had that little three,",
  "[06:59] four-minute exchange, they're like,",
  "[07:00] Man, that was awesome. I couldn't do",
  "[07:02] that before because I was so weak and I",
  "[07:04] hadn't developed my my shoulder",
  "[07:05] strength. I didn't have the mobility to",
  "[07:06] do that. Like, wow, it's a moment. What",
  "[07:09] else would it be? Maybe it's um you",
  "[07:11] know, bending over to tie my shoe. I",
  "[07:12] felt like I was getting out of breath",
  "[07:14] because I had to like hold my hold my",
  "[07:16] gut in so I could lean over to tie my",
  "[07:18] shoes. That's gone now. Like what if",
  "[07:20] there was a world where you just put",
  "[07:21] both of them on and you could do it",
  "[07:22] while you're standing, right? That's",
  "[07:23] that's not out of reach. It's just a",
  "[07:26] couple steps away from where you're at",
  "[07:27] right now. Right? So if I say that I can",
  "[07:29] describe all the things that someone",
  "[07:31] might experience and then denote that",
  "[07:33] they feel better without saying you're",
  "[07:35] going to feel better. And so this",
  "[07:37] applies for each of these elements of",
  "[07:39] copy. And this is what makes copy",
  "[07:41] potent. It's the specificity because you",
  "[07:43] want someone to understand it within",
  "[07:45] their own context of like, man, I've had",
  "[07:47] that happen. And that's real. That's",
  "[07:49] what makes you copy. And if that little",
  "[07:52] copy tip was helpful for you, then I",
  "[07:54] have pages and pages of of things that",
  "[07:56] have helped me make uh good ads uh",
  "[07:59] inside of the run paid ads chapter uh in",
  "[08:04] page 129. So, I talk about um one, how",
  "[08:06] paid ads work obviously, but secondly,",
  "[08:08] where do you how do you write the copy?",
  "[08:10] So I break down all the anatomy of ads",
  "[08:12] in all of this. All these pages I'm",
  "[08:13] talking about all of this is how you can",
  "[08:15] make the ad. And so this is the level",
  "[08:17] one",
  "[08:18] framework. The level two that you put on",
  "[08:20] top of this is who and when this is the",
  "[08:24] what which again I also cover in the",
  "[08:26] book. So we could talk about the",
  "[08:27] prospect but we could also talk about",
  "[08:29] that prospect status with regards to",
  "[08:30] their spouse. Talk about with regards to",
  "[08:32] their kids, talk about with regards to",
  "[08:34] their frenemies, their rivals, their",
  "[08:36] competitors, right? What is what are all",
  "[08:38] these plus and minuses with regards to",
  "[08:40] that that rival dad across the street or",
  "[08:42] that rival business, right? What what do",
  "[08:44] all those look like? And then how do we",
  "[08:46] pace that for today? But then also the",
  "[08:48] future, what does the future look like",
  "[08:49] when things don't go the right way? Ooh,",
  "[08:51] well that's going to be the bottom side.",
  "[08:53] That's what happens if you don't take",
  "[08:54] action, right? On the flip side, what",
  "[08:55] does the future look like if things go",
  "[08:57] well? Right? So we can play it out",
  "[08:58] today, but also play it out tomorrow.",
  "[09:00] And this gives you unlimited different",
  "[09:01] angles to make the meat of your ad more",
  "[09:04] compelling. And then the third thing is",
  "[09:05] obviously the call to action which you",
  "[09:07] want it to be as clear as humanly",
  "[09:08] possible and tell them exactly what you",
  "[09:09] want them to do and what will happen",
  "[09:11] next. It's a key point that a lot of",
  "[09:13] people miss. Not only do you want to say",
  "[09:14] it, you want it to be demonstrated in",
  "[09:15] the ad. So if I want someone to go to",
  "[09:16] the next page, when I say go to the next",
  "[09:18] page, I want the go to the next page to",
  "[09:19] be visible because that way what happens",
  "[09:22] is you have congruence. So and that has",
  "[09:24] a couple levels of persuasion there. So",
  "[09:26] number one in terms of congruence is",
  "[09:27] people say okay I have set my",
  "[09:29] expectations and they click and then",
  "[09:30] their expectations are met and then what",
  "[09:32] do you know? you have way fewer people",
  "[09:34] who bounce off the page because the page",
  "[09:35] looks exactly like I expected it to. Now",
  "[09:38] what else happens? The person who",
  "[09:40] actually made the recommendation, who",
  "[09:41] made the suggestion to go to the page",
  "[09:43] also increases in influence because when",
  "[09:45] you say something's going to happen and",
  "[09:46] then it happens, the person consciously",
  "[09:49] or subconsciously doesn't matter.",
  "[09:50] Science works either way. They will",
  "[09:52] believe the next thing you predict with",
  "[09:54] greater certainty. And so wouldn't you",
  "[09:57] want people to be like, man, when that",
  "[09:58] guy says something's gonna happen,",
  "[09:59] that's what happens. that precedes or",
  "[10:02] plants the seed for the sale that will",
  "[10:04] inevitably come down the road. Now, once",
  "[10:07] we have our ads, so now we're getting",
  "[10:09] we're getting eyeballs, right? People",
  "[10:10] are seeing the ads and then what are",
  "[10:12] they doing? They're taking an action.",
  "[10:14] All right, so this is my world's",
  "[10:15] terrible mouse click. They click on the",
  "[10:18] ad. I don't know, our little mouse is on",
  "[10:19] fire, but we're just going to go with",
  "[10:20] it. All right, the next step in this",
  "[10:22] process is going to be the opt-in,",
  "[10:25] right? We want them to give us their",
  "[10:27] their information for something. and",
  "[10:29] what are they going to give us the",
  "[10:30] information for? So, typically it's",
  "[10:31] going to be a lead magnet of some sort.",
  "[10:33] Now, people have this big issue with",
  "[10:34] like ah lead magnets are dead or lead",
  "[10:37] magnets, you know, are are alive. I'll",
  "[10:40] tell you this, bad lead magnets are",
  "[10:42] dead. Good lead magnets certainly are",
  "[10:45] alive and most lead magnets suck. And",
  "[10:48] so, it's unsurprising that the vast",
  "[10:50] majority of people who start to run ads",
  "[10:51] the first time don't make money because",
  "[10:53] their ads suck. And the first time you",
  "[10:55] take a sales call, you probably suck",
  "[10:56] because you don't know how to take a",
  "[10:57] sales call. And the first lead magnet",
  "[10:59] you make will probably suck, too. Now, I",
  "[11:01] want to give you, in my opinion, the",
  "[11:03] best lead magnet that I've ever seen in",
  "[11:05] my whole life. All right? And so, it was",
  "[11:06] actually in the dating space, and it was",
  "[11:08] called uh how to know if a girl wants",
  "[11:10] you to kiss her. Okay? Now, who wouldn't",
  "[11:12] want to know if a girl wants to wants",
  "[11:15] you to kiss her, right? And so, the",
  "[11:17] simple answer to that, and this is the",
  "[11:18] lead magnet, is try to brush her hair",
  "[11:21] behind her ear. And if she moves her",
  "[11:24] head away, then she doesn't want to kiss",
  "[11:25] you. If she doesn't move her head at all",
  "[11:27] or moves her head towards your hand,",
  "[11:28] then she does. Very simple. All right,",
  "[11:32] but the beauty of this is like, wait, so",
  "[11:34] that's that could be a lead magnet. Of",
  "[11:36] course, it could be a lead magnet. We",
  "[11:37] want to solve the tiniest problem we",
  "[11:39] possibly can for the prospect and",
  "[11:41] completely solve it and blow them away.",
  "[11:43] Now, some people are like, I made this",
  "[11:44] full course. And there's nothing wrong",
  "[11:45] with that, to be clear. I've got a whole",
  "[11:47] bunch of them on my site. The thing is",
  "[11:48] is there's going to be a certain amount",
  "[11:50] of information that is required in order",
  "[11:52] for a customer to make a decision.",
  "[11:53] Period. Right? I would toss out the idea",
  "[11:55] of emotional buyer, logical buyer, and",
  "[11:57] just replace that. And this is how I",
  "[11:59] think about it as high information and",
  "[12:01] low information. How much information",
  "[12:03] does someone need in order to make a",
  "[12:04] purchasing decision? Some people need",
  "[12:06] less, some people mean more. But if you",
  "[12:08] provide more to everyone, you will close",
  "[12:09] more people overall. And so, a lot of us",
  "[12:12] are trying to add to straight money. And",
  "[12:15] there are going to be those people who",
  "[12:16] will just see an ad, watch a video, and",
  "[12:19] then buy something. That happens. They",
  "[12:21] are the minority. They are the crazy",
  "[12:22] people. And we are grateful for them",
  "[12:23] because they allow all of the machines",
  "[12:25] to work. But for the other 97% of",
  "[12:28] people, they usually need a little bit",
  "[12:30] more time, a little bit more information",
  "[12:31] in order to make the decision. And we",
  "[12:33] have to facilitate that. So there's",
  "[12:34] going to be two paths that people are",
  "[12:36] going to selfidentify as we go through",
  "[12:37] through this to maximize our",
  "[12:39] monetization of the advertising that we",
  "[12:41] do to make the most money. Now, the lead",
  "[12:44] magnet I just explained, which was just",
  "[12:45] have, you know, have the girl brush her",
  "[12:47] uh sorry, brush the girl's hair behind",
  "[12:48] her ear. You can fill it out. So, what",
  "[12:50] what type of lead magnet is this? So,",
  "[12:53] what I gave you is a one step to a",
  "[12:55] multi-step solution. So, most people who",
  "[12:57] are in the dating space aren't looking",
  "[12:58] to just get a kiss, right? They're",
  "[13:00] looking to find more dates. They're",
  "[13:01] looking to, you know, eventually find a",
  "[13:03] wife. Uh they're going to have to get",
  "[13:04] into a relationship. They're going to",
  "[13:05] maybe get married later. So, there's all",
  "[13:07] these other problems that are going to",
  "[13:08] have to happen outside of just figuring",
  "[13:10] out if a girl wants to kiss you. If I",
  "[13:12] don't have dates, I don't care. Now,",
  "[13:14] this is neat, but I still have other",
  "[13:16] problems I need to solve. But if you",
  "[13:17] accurately solve that problem, because",
  "[13:18] I'm like, I can understand why that",
  "[13:20] would work. Then what do you think I'm",
  "[13:21] gonna do next? I'm gonna believe that",
  "[13:23] you could probably help me solve my",
  "[13:24] other problems. So what I just outlined,",
  "[13:27] you can come in real quick. So this is",
  "[13:29] page 32 of the leads book, is the",
  "[13:32] problem solution cycle, right? And",
  "[13:33] there's many, many problem solution",
  "[13:35] cycles that exist within a larger goal.",
  "[13:37] The bigger the goal, the more problem",
  "[13:38] solutions they have to go through,",
  "[13:39] right? And so our lead magnitude has to",
  "[13:41] solve one of these little problem",
  "[13:42] solutions. So the little teaching the",
  "[13:44] girl, you know, teaching the guy how to",
  "[13:45] know if the girl wants to kiss him. It's",
  "[13:46] not the big loop. It's just one of these",
  "[13:48] tiny itty bitty loops. That's all it is.",
  "[13:50] But now I think, well, who helped me",
  "[13:51] solve that one? I'll bet you he could",
  "[13:53] help me solve the rest of them. Now,",
  "[13:54] what type of lead magnet is this? So the",
  "[13:56] type lead, you could reveal a problem,",
  "[13:58] which would be like the reason that",
  "[13:59] you're not getting responses in your DMs",
  "[14:01] is because of this. So if I show them a",
  "[14:03] framework for what a DM supposed to be,",
  "[14:04] I've revealed the problem of why they're",
  "[14:06] not getting responses. Now, the other",
  "[14:08] side of this is that I could say, Hey,",
  "[14:09] I'm going to give you a free trial of my",
  "[14:11] dating thing. like this is another type",
  "[14:12] of lead magnet. Now, this one is",
  "[14:14] actually step three or type three of",
  "[14:16] lead magnets, which is I'm giving away",
  "[14:18] one step of a multi-step process to get",
  "[14:21] an outcome, right? You're not just",
  "[14:23] trying to get a girl to kiss you. You",
  "[14:25] have to get responses and you have to",
  "[14:27] set up dates and then you have to know",
  "[14:28] how to talk on the dates. You have to",
  "[14:29] know how to flirt beforehand and",
  "[14:31] afterhand and I don't know what",
  "[14:32] afterhand is, but apparently it's a",
  "[14:33] thing, right? And so, you got you got",
  "[14:35] after it and then it's like, how do I do",
  "[14:37] the second date? How do I do the third",
  "[14:37] date? What are smooth ways to to uh you",
  "[14:40] know proposition a woman to whatever you",
  "[14:42] get my idea. I'll stop there, you know,",
  "[14:44] fill the rest in with your imagination,",
  "[14:46] you know, and then propose. There we go.",
  "[14:47] We just went straight to marriage,",
  "[14:48] right? The whole thing is there's a lot",
  "[14:50] of problems that are going to happen in",
  "[14:51] this process and we don't need to solve",
  "[14:52] them all. Think about think about a date",
  "[14:53] a dating person who's like here's how to",
  "[14:55] go from zero to married, right? Like",
  "[14:57] that would be a lot. Like we just have",
  "[14:59] to solve the problem that's in front of",
  "[15:00] them today. Now, one of the other issues",
  "[15:03] with the lead magnet is is it made for",
  "[15:05] the right avatar? And this is a big one",
  "[15:06] and this like people mess this one up a",
  "[15:08] lot. All right. And so they're like,",
  "[15:10] Okay, well, how to make your first how",
  "[15:12] to get your first five clients, right? I",
  "[15:14] have some videos for that. But that's",
  "[15:15] not my main avatar. Now, I am willing to",
  "[15:17] help people out who are getting started,",
  "[15:19] and that's okay. That's why I make those",
  "[15:20] things. But is it is somebody who's just",
  "[15:22] getting started my avatar today? No. But",
  "[15:24] I'm betting on the fact that they will",
  "[15:25] be years from now. But not because I",
  "[15:27] want to give something to that person",
  "[15:28] today. Right? And so if you have a",
  "[15:31] spectrum of customers that you could",
  "[15:33] potentially service, you want to make",
  "[15:34] sure the lead magnet is perfectly fit",
  "[15:36] for the perfect customer that you want.",
  "[15:38] And if you haven't gotten clear on the",
  "[15:39] type of customer you want, then you're",
  "[15:41] certainly not going to be able to make",
  "[15:42] the right lead magnet. Now, I have a",
  "[15:43] free chapter. I think it's called uh you",
  "[15:44] go acquisition.com. I think it's called",
  "[15:47] avatar. I think that's what it is. But",
  "[15:48] if you go your first avatar",
  "[15:50] acquisition.com or I'm sure you can find",
  "[15:52] it, but basically if you're not sure how",
  "[15:53] to pick your avatar, that uh chapter",
  "[15:55] explains it. It was actually kind of",
  "[15:57] like a single that I released after the",
  "[15:59] offers book. I recommend you check it",
  "[16:00] out. Anyways, now once we have our lead",
  "[16:03] magnet, we have their information. So,",
  "[16:06] what is that going to lead to? We're",
  "[16:08] going to need to lead to something",
  "[16:09] that's going to sell them, right? Who's",
  "[16:10] going to warm up the prospect? All",
  "[16:12] right. And so, this is where we get our",
  "[16:15] video sales letter. This is a VSSL,",
  "[16:18] right? It's just a fancy term here.",
  "[16:20] Fancy fancy. By the way, if you want an",
  "[16:23] example of a lead magnet, this is one",
  "[16:25] that we have. So you can check this out.",
  "[16:26] So $100 million scaling grow map. This",
  "[16:28] is for business owners, right? So if",
  "[16:30] you're a business owner, you're trying",
  "[16:31] to scale, then you're going to be at one",
  "[16:32] of these 10 stages of scaling. And so",
  "[16:34] what problem can I solve for you today?",
  "[16:35] Well, if I can solve the current",
  "[16:36] constraint in your business and show",
  "[16:38] where uh this is, by the way, a reveal a",
  "[16:39] problem type of of lead magnet. So I",
  "[16:42] reveal the problem and then I also give",
  "[16:44] you the solution to do this. But the",
  "[16:45] thing is is if you see this and",
  "[16:46] sometimes even just being, oh my god,",
  "[16:48] this is exactly what I'm struggling with",
  "[16:49] right now. Then it probably increases",
  "[16:51] the likely that you think, okay, I think",
  "[16:52] this guy could help me out. Simple as",
  "[16:54] that. and it provides you more",
  "[16:56] information to eventually make a",
  "[16:57] decision. All right, so the lead magnet",
  "[16:59] sets the stage and attracts the exact",
  "[17:01] type of prospect that I want to work",
  "[17:03] with, right? Someone with",
  "[17:04] qualifications. But now we have to",
  "[17:06] convert them. All right, and this is",
  "[17:07] where our video sales letter comes into",
  "[17:10] play. All right, so the video sales",
  "[17:12] letter, the video that you have here is",
  "[17:14] probably one of the highest leveraged",
  "[17:15] things that you can create in terms of",
  "[17:17] sales aids, right? Like if you get on if",
  "[17:20] if a lot of times you're like, man, uh",
  "[17:21] you know, ads don't work for me. It's",
  "[17:23] not that ads don't work for you. It's",
  "[17:24] that you haven't put enough friction in",
  "[17:25] your process. And again, this is one of",
  "[17:27] those things everyone's afraid of.",
  "[17:28] Everyone's afraid of adding steps,",
  "[17:29] adding friction, adding questions,",
  "[17:30] adding qualifications, having people",
  "[17:32] watch things in order to make a",
  "[17:33] purchasing decision. But I promise you,",
  "[17:35] if you look at your customers over the",
  "[17:37] last however long, most of them, almost",
  "[17:40] all of them will not have immediately",
  "[17:43] bought something. Most of the times they",
  "[17:45] will have consumed an hour, 2 hours, 3",
  "[17:47] hours plus of information from you in",
  "[17:50] various formats before they decide to go",
  "[17:52] through this process and ultimately buy.",
  "[17:55] And so what we want to do is reverse",
  "[17:56] engineer and facilitate this. Like the",
  "[17:58] big finding I had when I was in gym",
  "[17:59] launch was that 78% of customers had had",
  "[18:02] consumed at least two long form uh",
  "[18:05] pieces of content. Now I had podcasts, I",
  "[18:07] had books, I had I had I had a group",
  "[18:09] that I had kind of the video version of",
  "[18:11] those podcasts. And so 78% had consumed",
  "[18:14] at least two. So in thinking about this",
  "[18:16] I was like okay so my average piece of",
  "[18:19] long form content at the time was",
  "[18:20] something the neighborhood of like maybe",
  "[18:21] 17 to 20 minutes. So basically people",
  "[18:24] had to consume call it an hour right of",
  "[18:26] information from me in order to to be",
  "[18:29] willing to book a call and be warm and",
  "[18:31] potentially buy. And so I was like okay",
  "[18:33] if that's what it takes why don't I try",
  "[18:35] and force people to do that to become",
  "[18:37] somebody who is likely to buy. If that's",
  "[18:39] what 78% of people do in before buying,",
  "[18:42] well then why don't I get a 100% of my",
  "[18:43] people to do the thing that 78% do that",
  "[18:45] are the ultimate buyers. That's the",
  "[18:47] idea. So if you're like, okay, VSSL,",
  "[18:50] what do I put inside this video? I'm",
  "[18:52] going to walk you through a very simple",
  "[18:54] frame. There's there's a bunch of",
  "[18:55] different, you know, versions of VSSLs",
  "[18:57] that you can run. I'm not going to get",
  "[18:58] into that today, but people over",
  "[19:00] complicate this. All right? They want to",
  "[19:02] make this seem like this big box of",
  "[19:04] black magic. And I've made so many video",
  "[19:07] sales letters in my life that I can tell",
  "[19:09] you there is no big box of magic. Um,",
  "[19:12] and I'll give you two different",
  "[19:13] structures that work really well. Okay,",
  "[19:15] so structure one is actually very",
  "[19:18] similar to a YouTube video. So you're",
  "[19:20] going to go the five Ps, which is proof,",
  "[19:23] promise, pain, plan, picture. Okay, so",
  "[19:28] what does this mean? It means that I",
  "[19:29] need to make some promise that they're",
  "[19:31] going to get from this video. I need to",
  "[19:32] talk about the pain to demonstrate that",
  "[19:33] I know where they're at right now. I",
  "[19:34] need to give them proof that they that",
  "[19:36] they why they should believe me. And",
  "[19:38] then I'm going to lay out the plan of",
  "[19:39] how I'm going to help them solve it. And",
  "[19:40] then usual",
];
